[tool.poetry]
name = "usad"
version = "0.1.0"
description = ".."
authors = ["xy"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
seaborn = "^0.13.1"
ipykernel = "^6.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"